# ~/.config/starship.toml

format = "$time $directory $git_branch ${custom.gcloud} ${custom.kube} \n$character"

[custom.gcloud]
command = "$HOME/.local/bin/gcloud-prompt"
when = "true"
format = "on [$output]($style) "
style = "bold blue"

[custom.kube]
command = "$HOME/.local/bin/kube-context-prompt"
when = "true"
format = "via [☸ $output]($style) "
style = "bold cyan"

[time]
disabled = false
format = "[$time]($style) "
time_format = "%H:%M"

[directory]
truncation_length = 3
fish_style_pwd_dir_length = 2
# [directory.substitutions]
# '/Users/you/scripts/' = '📂 Scripts'
# '/Users/you/projects/work' = '📂 Work'
# 'Users/you' = '📂 Home'
# 'Users/you/Downloads' = '📂 Downloads'

[git_branch]
symbol = ""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
