model_list:
  - model_name: gemini-3.5-flash
    litellm_params:
      model: vertex_ai/gemini-3.5-flash
      vertex_project: "os.environ/GCP_PROJECT_ID"
      vertex_location: "global"
  - model_name: gemini-3.1-pro-preview
    litellm_params:
      model: vertex_ai/gemini-3.1-pro-preview
      vertex_project: "os.environ/GCP_PROJECT_ID"
      vertex_location: "global"
  - model_name: claude-opus-4-8
    litellm_params:
      model: vertex_ai/claude-opus-4-8
      vertex_project: "os.environ/GCP_PROJECT_ID"
      vertex_location: "global"
  - model_name: claude-sonnet-4-6
    litellm_params:
      model: vertex_ai/claude-sonnet-4-6
      vertex_project: "os.environ/GCP_PROJECT_ID"
      vertex_location: "global"
